### ISSUE TITLE
Passing `preview: false`  doesn't seem to do anything.

### ISSUE THREAD

**Issue by ahwelgemoed** [discord/react-dnd-accessible-backend#2]
Hey - First off, thanks for an awesome lib.

## The issue

Passing `preview: false`  doesn't seem to do anything.

I create my own preview and style it, but on keyboard interaction I get 2 "Dragging Items" as preview is not "turing off" the default one

I have cloned the lib and ran the example locally and changing `DND_OPTIONS` to this , doesn't seem to do anything.

```js
const DND_OPTIONS = {
  backends: [
    {
      id: "keyboard",
      backend: KeyboardBackend,
      context: { window, document },
      options: {
        announcerClassName: "announcer",
      },
      preview: false, // Note true to false
      transition: KeyboardTransition,
    },
  ],
};
```

I did some exploring and seems that you create your own preview, _(please correct me if Im wrong)_ and seemingly passing `preview:false` is lost as its not consumed in `KeyboardBackend.tsx` by `BackendFactory` type.

## Possible Solution
Pass a preview boolean in options object and consume it and based on that boolean display `createDragPreview`

## Notes
Let me know if you would like me to do a PR I would happily add it in, but I didn't want to do it spontaneously as there is no `CONTRIBUTE.md`

**Comment by 5denovembro** [comment]
i just want pleace, for me and my family segurity

**Comment by faultyserver** [comment]
It's certainly taken long enough to get around to this, my apologies.

I dug into it and I don't think this library _can_ actually respect that field because of the way `react-dnd-multi-backend` is implemented.

Also, for the sake of supporting consumers that don't use that library, I've gone ahead and just made it an option directly on the backend that can be configured instead. That should allow you to hide the previews, though it unfortunately requires the additional, different configuration.
